### PR TITLE
Fixed issue breaking hash expressions with plain objects

### LINKED ISSUE #325: Hash expressions don't work with plain objects
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Rendering a hash expression that uses a primitive object as its data source does not work.

__Expected results:__
https://jsfiddle.net/3tzxnr5e/2/

__Actual results:__
https://jsfiddle.net/3tzxnr5e/1/

### PR DESCRIPTION
**Pull request by imaustink**
When passing `Array`s to each, they were delegated to `utils.getItemsFragContent`, which does not support hash expression and should not be used in this case.

When passing `Object`s to each, the last case of `expr instanceof Object` handles the iteration, which also did not support hash expressions.

Closes #325

### CODE REVIEW

File: test/stache-test.js [hunk 1]
```diff
@@ -6580,6 +6594,44 @@ function makeTest(name, doc, mutation) {
 		equal(warn1(), 0);
 		equal(warn2(), 0);
 	});
+
+	test('#each with call expression and plain array should not use utils.getItemsFragContent', function(){
```
Comment (phillipskevin) [inline test/stache-test.js]: The other tests for arrays+call expressions+hash expressions test that this works, I don't think it's necessary to test this implementation detail.

File: helpers/core.js [hunk 2]
```diff
@@ -166,6 +164,14 @@ var helpers = {
 				if (asVariable) {
 					aliases[asVariable] = expr[key];
 				}
+				if (!isEmptyObject(hashOptions)) {
+					if (hashOptions.value) {
+						aliases[hashOptions.value] = expr[key];
+					}
+					if (hashOptions.key) {
+						aliases[hashOptions.key] = key;
+					}
```
Comment (phillipskevin) [inline helpers/core.js]: How about `hashOptions.index`?

File: helpers/core.js [hunk 3]
```diff
@@ -114,15 +114,13 @@ var helpers = {
...
-			result = utils.getItemsFragContent(expr, options, options.scope, asVariable);
-			return options.stringOnly ? result.join('') : result;
-		}
-		else if(isIterable(expr)) {
+		if(isIterable(expr)) {
 			result = [];
 			each(expr, function(value, key){
 				aliases = {
-					"%key": key
+					"%key": key,
```
Comment (phillipskevin) [inline helpers/core.js]: I don't think this needs to handle objects, since there is already a branch below for `expr instanceof Object`. Maybe the check here should just be `Array.isArray(expr)`.

Comment (imaustink) [reply helpers/core.js]: Very good point. Can you see any potential problems with just getting rid of the `expr instanceof Object` branch and letting this handle both? Seems like there is a lot duplicated logic for no reason.

File: helpers/core.js (hunk 2 above)
Comment (imaustink) [reply helpers/core.js]: Shouldn't that just be available when iterating over arrays? The docs say "`index`: The index of the current array item"

Comment (phillipskevin) [reply helpers/core.js]: I'm talking about the alias created when using hash expressions. So if you do something like

```
{{#each(items, val=value num=index)}}
```

File: helpers/core.js (hunk 3 above)
Comment (phillipskevin) [reply helpers/core.js]: The `isIterable(expr)` case doesn't cover plain objects.
