### PR TITLE
Named Partials render string result in stringOnly state

### LINKED ISSUE #710: Named Partials render with documentFragment in stringOnly state instead of expected string result
I understand this may be marked as "won't fix" or at least probably isn't a priority since there are ways to work around it and most wouldn't ever need it. I took a few swings at fixing it but didn't get far in the time I have.

__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Named partials (technically section renderer) produce document fragments even when stringOnly is true in the section its being rendered in (in a style tag, for example).
https://github.com/canjs/can-stache/blob/b530682034cf1e59285046df5475b57ce5e5b0b1/src/mustache_core.js#L291
"res" is a documentFragment at that line when a named partial is rendered inside of style tag.

The text representation should be rendered instead.

__Steps to reproduce:__

https://codepen.io/anon/pen/eqRVZG?&editable=true&editors=0011

__Expected results:__

contents of style tag should be the raw text produced by the render. (Note: "innerHTML" of the fragment produced would be incorrect in the browser because it escapes things like ">" automatically)

__Actual results:__

contents of the style tag is "[object DocumentFragment]"

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | latest
| Browser                    | chrome
| Operating system    | windows 10

Thank you for your time!
//James

### PR DESCRIPTION
**Pull request by cherifGsoul**
Fixes #710 

### The changes:
The logic changes are in this line
https://github.com/canjs/can-stache/blob/b530682034cf1e59285046df5475b57ce5e5b0b1/src/mustache_core.js#L293

- Check if the returning result of `branchRenderer` is a `DocumentFragment`  instance, in this case return the `textContent` of this result,  `""+res` doesn't cast `DocumentFragment` instance to string.

### CODE REVIEW

File: src/mustache_core.js [hunk 1]
```diff
@@ -289,8 +289,13 @@ var core = {
 				res = evaluator();
 			}
 
-
-			return res == null ? "" : ""+res;
+			if (res == null) {
+				return "";
+			}
+			if (res instanceof DocumentFragment) {
```
Comment (matthewp) [inline src/mustache_core.js]: instead of checking instanceof, check `res.nodeType === 11` which is a document fragment.

Comment (cherifGsoul) [reply src/mustache_core.js]: Updated!
