### PR TITLE
making Bracket expressions work with keys with multiple dots

### LINKED ISSUE #607: Bug: Cannot access DefineMap properties if they contain dot's
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
Cannot access a property on a DefineMap if the property has multiple `.` in it

https://codepen.io/mattchewone-the-looper/pen/pxpavm

__Steps to reproduce:__
- Create a property on a DefineMap which is itself a DefineMap
- Give it a key like `this.special.key` and a value
- Access that property within the stache

__Expected results:__
The properties value should be shown within the rendered template

__Actual results:__
Nothing, if you `console.log` the property you will see `undefined`

__Environment:__
CanJS V3

### PR DESCRIPTION
**Pull request by phillipskevin**
closes #607 .

### CODE REVIEW

File: src/expression-helpers.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ function computeHasDependencies(compute){
 function getObservableValue_fromDynamicKey_fromObservable(key, root, helperOptions, readOptions) {
 	// This needs to return something similar to a ScopeKeyData with intialValue and parentHasKey
 	var getKeys = function(){
-		return stacheKey.reads(("" + canReflect.getValue(key)).replace(".", "\\."));
+		return stacheKey.reads(("" + canReflect.getValue(key)).replace(/\./g, "\\."));
```
Comment (justinbmeyer) [inline src/expression-helpers.js]: could we just return [{key: canReflect.getValue(key) }]

```suggestion
		return [{key: ""+canReflect.getValue(key)}]
```

Comment (phillipskevin) [reply src/expression-helpers.js]: No, this would break functions. `stacheKey.reads("@toFixed")` -> `{ key: "toFixed", at: true }`.
