### PR TITLE
makes brackets able to work with literals

### LINKED ISSUE #207: Binding to a list index using bracket notation does not bind or errors
@kylegifford commented on [Tue May 30 2017](https://github.com/canjs/canjs/issues/3289)

if `test` is defined as `test: ['']`, then the following binding issues occur:

works:
```
<input {($value)}="test.0" />
{{test.0}}
```

works:
```
<input {($value)}="test['0']" />
{{test.0}}
```

errors in can-observation/reader:287:
```
<input {($value)}="test[0]" />
{{test.0}}
```

screenshot 2017-05-30 15 28 50
screenshot 2017-05-30 15 29 05

if `test` is defined as `test: { foo: [''] }`, then the following binding issues occur:

works:
```
<input {($value)}="test.foo.0" />
{{test.foo.0}}
```

doesn’t work (no error, just doesn't set the value):
```
<input {($value)}="test['foo']['0']" />
{{test.foo.0}}
```

errors in can-view-scope:109:
```
<input {($value)}="test['foo'][0]" />
{{test.foo.0}}
```

screenshot 2017-05-30 15 32 25

### PR DESCRIPTION
**Pull request by kylegifford**
Fixes #207

### CODE REVIEW

File: test/expression-test.js [hunk 1]
```diff
@@ -331,7 +331,7 @@ test("convertKeyToLookup", function(){
 
 
 test("expression.ast - [] operator", function(){
-	deepEqual(expression.ast("['propName']"), {
+	/*deepEqual(expression.ast("['propName']"), {
```
Comment (phillipskevin) [inline test/expression-test.js]: can you uncomment these tests?
