### PR TITLE
Fix using hash expressions inside call expressions

### LINKED ISSUE #326: Hash expressions don't work inside call expressions
If a hash expression is used inside a call expression, the following error is thown:
```
can.all.js:1610 Uncaught TypeError: callback.call is not a function
    at String.<anonymous> (VM1156 can.all.js:1610)
    at Object.eachListLike (VM1156 can.all.js:1591)
    at Object.eachIndex (VM1156 can.all.js:1557)
    at Object.eachKey (VM1156 can.all.js:1608)
    at forEach (VM1156 can.all.js:17241)
    at DefineMap.Construct.extend.forEach (VM1156 can.all.js:17244)
    at Compute.<anonymous> (VM1156 can.all.js:9190)
    at Observation.start (VM1156 can.all.js:3717)
    at Compute._on (VM1156 can.all.js:4565)
    at Compute.<anonymous> (VM1156 can.all.js:4671)
```
https://jsfiddle.net/3tzxnr5e/5/

### PR DESCRIPTION
**Pull request by imaustink**
Fixes #326

### CODE REVIEW

File: test/stache-test.js [hunk 1]
```diff
@@ -32,6 +32,8 @@ var makeArray = require('can-util/js/make-array/make-array');
 var joinURIs = require('can-util/js/join-uris/join-uris');
 var getBaseURL = require('can-util/js/base-url/base-url');
 var testHelpers = require('can-test-helpers');
+var canLog = require('can-util/js/log/log');
```
Comment (phillipskevin) [inline test/stache-test.js]: should this be `can-log` now?

File: src/expression.js [hunk 2]
```diff
@@ -53,6 +54,23 @@ function displayScopeWalkingWarning(key, scope, computeData, readOptions) {
 //!steal-remove-end
 
 // ## Helpers
+
+// ## Helpers
+
+var builtInHelpers = {
```
Comment (phillipskevin) [inline src/expression.js]: Let's try to reorganize this so we don't have to enumerate the helpers here. We should be able to export the helpers so we don't have to update this list if a new helper is added.

Comment (imaustink) [reply src/expression.js]: I was considering this earlier. If we simply export the helpers, it would include any helpers added by `registerHelper`. Can you foresee that causing problems?

File: test/stache-test.js (hunk 1 above)
Comment (imaustink) [reply test/stache-test.js]: Yes, it should. Updated.

File: src/expression.js (hunk 2 above)
Comment (imaustink) [reply src/expression.js]: Just tested and It breaks lots of tests if we export the helpers object directly so I used `assign` to copy the built-in helpers on init.

File: package.json [hunk 3]
```diff
@@ -55,6 +55,7 @@
     "can-event": "^3.6.0",
     "can-list": "^3.2.0",
     "can-map": "^3.3.0",
+    "can-stache-bindings": "^3.9.6",
```
Comment (phillipskevin) [inline package.json]: why was this added?

**Comment by imaustink** [comment]
Done!

**Comment by phillipskevin** [comment]
Merging master into your branch should fix the test failure.
