### PR TITLE
warn when partial is missing

### LINKED ISSUE #493: Should give a warning when a partial is not found
If we fail to find a partial, we get an error like this:

```
TypeError: el is null
```
here: 
https://github.com/canjs/can-stache/blob/58781049ab1fb63c5d69286a83fe9c7167163ee3/can-stache.js#L477

We should give a better warning explaining this.

This happens if you do something like:

```
import Component from "can-component";
import itemRenderer from "./items.stache";


Component.extend({
  ViewModel: {
    items: {
      default() { return [ "one", "two" ]; }
    },

    itemRenderer: itemRenderer
  },

  view: `
    {{#each(items)}}
        {{> itemRenderer}}
    {{/each}}
  `
});
```

This should use `{{> scope.root.itemRenderer}}`, but it's very difficult to figure this out based on the error.

### PR DESCRIPTION
**Pull request by cherifGsoul**
Closes #493

### CODE REVIEW

File: test/warnings-test.js [hunk 1]
```diff
@@ -206,3 +207,16 @@ testHelpers.dev.devOnlyTest("Variable not found warning should suggest correct k
 	Scope.prototype.getPathsForKey = origGetPaths;
 
 });
+
+testHelpers.dev.devOnlyTest("Should give a warning when a partial is not found #493", function () {
+	var template,
+		items = new DefineList(['one', 'two']),
+		teardown = testHelpers.dev.willWarn('Unable to find partial "itemRenderer"');
+
+	template = stache("{{#each(items)}} {{> itemRenderer}} {{/each}}");
```
Comment (justinbmeyer) [inline test/warnings-test.js]: Why is each needed?  Also `DefineList`?  If there's a way to do this with more minimal example, please do so.

Comment (cherifGsoul) [reply test/warnings-test.js]: Done!

**Comment by chasenlehara** [comment]
@cherifGsoul It looks like there are some merge conflicts now.

**Comment by cherifGsoul** [comment]
@chasenlehara fixed!

File: can-stache.js [hunk 2]
```diff
@@ -563,6 +563,12 @@ stache.from = mustacheCore.getTemplateById = function(id){
 		var el = DOCUMENT().getElementById(id);
 		if(el) {
 			templates[id] = stache("#" + id, el.innerHTML);
+		} else {
+			//!steal-remove-start
+			if (process.env.NODE_ENV !== 'production') {
```
Comment (phillipskevin) [inline can-stache.js]: This doesn't seem like the correct place to put this warning. This will cause the same warning if you do `stache.from("foo")` and there is no `<script type='text/stache' id='foo'>` on the page. I think `Unable to find partial 'foo'` will be pretty confusing in this case since `stache.from` isn't about partials.

I think the correct fix is inside `makeLiveBindingPartialRenderer`, somewhere in here:

https://github.com/canjs/can-stache/blob/bd91e957535d4aea80b31ac825ba95795b8d1df7/src/mustache_core.js#L223-L230

This would also allow us to add the filename and lineNumber in the warning, which would make it much easier to track down what you're doing wrong.

Comment (cherifGsoul) [reply can-stache.js]: @phillipskevin Thank you, I changed the fix as you reviewed

File: src/mustache_core.js [hunk 3]
```diff
@@ -225,7 +225,15 @@ var core = {
...
 						} else {
 							var domRenderer = core.getTemplateById(localPartialName);
-							return domRenderer ? domRenderer(partialScope, {}, nodeList) : getDocument().createDocumentFragment();
+							if (domRenderer) {
+								return domRenderer(partialScope, {}, nodeList);
+							}
+
+							//!steal-remove-start
+							if (process.env.NODE_ENV !== 'production') {
+								dev.warn('Unable to find the partial "' + localPartialName + '" in ' + state.filename + ':' + state.lineNo);
```
Comment (phillipskevin) [inline src/mustache_core.js]: I think you are missing a `steal-remove-end`.

Also, I think this code would make more sense if you keep the `return` code how it was and make the warning separate.

```js
// !steal-remove-start
if (process.env.NODE_ENV !== 'production') {
  if (!domRenderer){
    ...
  }
}
// !steal-remove-end
```

retrun domRenderer ? ...;

Comment (phillipskevin) [reply src/mustache_core.js]: Also, can you add the filename and lineNumber?

Comment (cherifGsoul) [reply src/mustache_core.js]: It was returned before I changed, no? `domRenderer ? domRenderer(partialScope, {}, nodeList) : getDocument().createDocumentFragment()`

Comment (cherifGsoul) [reply src/mustache_core.js]: @phillipskevin fixed!

File: src/mustache_core.js [hunk 4]
```diff
@@ -225,6 +225,13 @@ var core = {
 							return localPartialName(partialScope, {}, nodeList);
 						} else {
 							var domRenderer = core.getTemplateById(localPartialName);
+							//!steal-remove-start
+							if (process.env.NODE_ENV !== 'production') {
+								if (!domRenderer) {
+									dev.warn('Unable to find the partial "' + localPartialName + '" in ' + state.filename + ':' + state.lineNo);
```
Comment (phillipskevin) [inline src/mustache_core.js]: can you add the filename and lineNumber?

Comment (cherifGsoul) [reply src/mustache_core.js]: @phillipskevin Done!
