### PR TITLE
LetContext as Call Expressions

### LINKED ISSUE #649: Can't call partials stored in LetContext as Call Expressions
This works:
```
    {{< foo }}
      This is foo
    {{/ foo }}

    <p>{{ scope.templateContext.partials.foo() }}</p>
```

...and this works:

```
    {{< foo }}
      This is foo
    {{/ foo }}

    {{ let bar = scope.templateContext.partials.foo }}

    <p>{{ bar "baz" }}</p>
```

...but this doesn't work:

```
    {{< foo }}
      This is foo
    {{/ foo }}

    {{ let bar = scope.templateContext.partials.foo }}

    <p>{{ bar() }}</p>
```

In this case, the partial is called, but not rendered. I'm not sure why.

### PR DESCRIPTION
**Pull request by cherifGsoul**
fixes #649

### CODE REVIEW

File: expressions/call.js [hunk 1]
```diff
@@ -71,8 +71,10 @@ Call.prototype.value = function(scope, helperOptions){
 
 	var computeFn = function(newVal){
 		var func = canReflect.getValue( method );
-
 		if(typeof func === "function") {
+			if (canReflect.isObservableLike(func)) {
```
Comment (justinbmeyer) [inline expressions/call.js]: I wonder if this could get further recursive ...
