### PR TITLE
Hash expressions used in each helper should not warn

### LINKED ISSUE #461: `can-stach/expressions/lookup.js` throws false positive warnings.
__How often can you reproduce it?__ 

- Always

__Description:__
`can-stach/expressions/lookup.js` throws false positive warnings like these:
```
can-stache/expressions/helper.js: Unable to find helper "label".
```

__Steps to reproduce:__
https://jsbin.com/nutotejuno/edit?html,js,console

In my case I narrowed it down to an `each` loop.
```
{{#each(panels, panel=value)}}
    {{panel.label}}
{{/each}}
```

Or:
```
{{#each(panels)}}
    {{label}}
{{/each}}
```

__Expected results:__
No console warnings.

__Actual results:__
Console warnings:
```
can-stache/expressions/lookup.js: Unable to find key "value".
can-stache/expressions/lookup.js: Unable to find key "panel.label".
```

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  | 4.0.1
| Browser                    | Chrome 64
| Operating system    | Mac OS

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #461 

The jsbin attached to the issue https://jsbin.com/nutotejuno/edit?html,js,console shows more warnings due to a mistake instantiating the scope map:

```js
var appViewModel = new can.DefineMap({
  // this should be `panels: panels` 
  panels: {
    // the DefineMap should be extended for this to work, 
    // that's why can-stache can't find panel.label when rendering the template.
    default: panels 
  }
});
```

Once the issue mentioned above is fixed ^ the only warning shows in about `value` which is fixed by this PR.

screen shot 2018-03-01 at 1 34 50 pm

### CODE REVIEW

File: expressions/call.js [hunk 1]
```diff
@@ -18,20 +18,22 @@ var Call = function(methodExpression, argExpressions){
...
 		if(arg.expr instanceof Hashes){
 			assign(hashExprs, arg.expr.hashExprs);
 		}
-		var value = arg.value.apply(arg, arguments);
-		args.push({
-			// always do getValue unless compute is false
-			call: !arg.modifiers || !arg.modifiers.compute,
-			value: value
-		});
+		if (typeof ignoreArgLookup !== "function" || !ignoreArgLookup(arg)) {
```
Comment (justinbmeyer) [inline expressions/call.js]: typeof check happening over and over
